// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc89eQFFMRyBqY43UHcifI8okI_j9Kghk',
    appId: '1:583620562052:web:f4a950c45cd10674a3c6d1',
    messagingSenderId: '583620562052',
    projectId: 'aforg-dart',
    authDomain: 'aforg-dart.firebaseapp.com',
    storageBucket: 'aforg-dart.appspot.com',
    measurementId: 'G-D1GE737HZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdPYDJUx5n5kUOEc4oSwTPAqvHLC9J9hc',
    appId: '1:583620562052:android:009c4512b4afb4d8a3c6d1',
    messagingSenderId: '583620562052',
    projectId: 'aforg-dart',
    storageBucket: 'aforg-dart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEtsj4YZVaSTZD70pvW6MHsOHJWFWhzR4',
    appId: '1:583620562052:ios:8fe26059eb52c23aa3c6d1',
    messagingSenderId: '583620562052',
    projectId: 'aforg-dart',
    storageBucket: 'aforg-dart.appspot.com',
    iosBundleId: 'com.example.afg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEtsj4YZVaSTZD70pvW6MHsOHJWFWhzR4',
    appId: '1:583620562052:ios:0ceddc8991e8ddf6a3c6d1',
    messagingSenderId: '583620562052',
    projectId: 'aforg-dart',
    storageBucket: 'aforg-dart.appspot.com',
    iosBundleId: 'com.example.afg.RunnerTests',
  );
}
